# Generated by Django 4.0.dev20210427084335 on 2021-05-01 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('uid', models.CharField(max_length=200)),
                ('sourceType', models.CharField(blank=True, choices=[('U', 'URL'), ('T', 'TEXT')], max_length=1, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('wcImage', models.FileField(blank=True, null=True, upload_to='')),
                ('createDate', models.DateField(default=datetime.datetime(2021, 5, 1, 6, 57, 37, 871178))),
                ('updateDate', models.DateField(default=datetime.datetime(2021, 5, 1, 6, 57, 37, 871211))),
            ],
        ),
    ]
