# Generated by Django 4.0.dev20210427084335 on 2021-05-01 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0002_alter_imageupload_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 9, 43, 13, 94354)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 9, 43, 13, 94387)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('creaditDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordcloudAPI.imageupload')),
            ],
        ),
    ]
