# Generated by Django 4.0.dev20210427084335 on 2021-05-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0003_alter_imageupload_createdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creaditDate',
            new_name='createDate',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 10, 30, 34, 70531)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 10, 30, 34, 70561)),
        ),
    ]
