# Generated by Django 4.0.dev20210427084335 on 2021-05-01 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0004_rename_creaditdate_comment_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='wcImageURL',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 11, 6, 4, 635112)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 11, 6, 4, 635147)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='wcImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
