# Generated by Django 4.0.dev20210427084335 on 2021-05-02 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0007_alter_imageupload_createdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('sourceType', models.CharField(blank=True, choices=[('U', 'URL'), ('T', 'TEXT')], max_length=1, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=models.CharField(max_length=100))),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 8, 54, 58, 494395)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 8, 54, 58, 494429)),
        ),
    ]
