# Generated by Django 4.0.dev20210427084335 on 2021-05-02 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0009_alter_imageupload_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='imageURL',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 11, 40, 41, 283082)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 11, 40, 41, 283112)),
        ),
    ]
