# Generated by Django 4.0.dev20210427084335 on 2021-05-02 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloudAPI', '0010_wordcloud_imageurl_alter_imageupload_createdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcloud',
            name='image',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 55, 43, 728162)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 55, 43, 728198)),
        ),
    ]
